### ISSUE TITLE
Plugin main file parts

### ISSUE THREAD

**Issue by szepeviktor** [leoloso/PoP#323]
Hello Leo!
Looking at
https://github.com/leoloso/PoP/blob/master/layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/graphql-api.php
I recall my recent research on main file parts.
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md

Sample code
https://github.com/szepeviktor/small-project/blob/master/plugin-name.php

I hope you benefit from the research 🚀

**Comment by leoloso** [comment]
Hi Viktor!

Thanks for your suggestion, but could you be a bit more specific on what you think `graphql-api.php` needs?

I need to load the language domain, yep I had forgotten about that one.

Otherwise, I think it's already alright. For instance, it already deals with preventing double activation.

From your file, the one thing I could add is this:

```php
if (
    (new Requirements())
        ->php('7.4')
        ->wp('5.2')
   ) {
    // ...
}
```

But then, I already have that info in the header, and I'd need to modify it when downgrading from PHP 7.4 to 7.1... so maybe I can do without it

Anything else?

**Comment by szepeviktor** [comment]
I'm try to leave all WordPress/PHP 4-rooted things behind.

- immutable container (`Config`) instead of global constants
- support Composer-managed WordPress installations where `vendor/` is not inside the plugin
- no immediate execution (`https://www.youtube.com/watch?v=F63Sldex_8I`) but hooking into `plugins_loaded`

Everything is listed on the above link in theory and also in practice.

**Comment by szepeviktor** [comment]
⚠️ It is sample code, not a wise thing to copy.
You can add/remove features as needed.
