### ISSUE TITLE
Hello 1 000 000 lines monster!

### ISSUE THREAD

**Issue by szepeviktor** [leoloso/PoP#431]
# 👹 

1. ~6800 duplicated files
2. 600k PHP
3. 300k JSON
4. WordPress core has only ~2000 files and 700k lines

```
viktor@mail:~/src/Forks/PoP$ cloc.pl .
   18279 text files.
   12345 unique files.
    6343 files ignored.

github.com/AlDanial/cloc v 1.80  T=24.53 s (486.8 files/s, 54677.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
PHP                           9788          69293          84121         632231
JSON                           256              0              0         328382
JavaScript                     876           9638          10644          30841
Markdown                       584          16277              0          29899
PO File                         57          29052          68912          14880
CSS                            134           1409            575           9347
YAML                           213            532            125           2804
XML                              1             80            124            944
HTML                            11             49             37            478
Sass                            17             46             52            357
Bourne Shell                     4             37             70            105
INI                              1              1              3              8
-------------------------------------------------------------------------------
SUM:                         11942         126414         164663        1050276
-------------------------------------------------------------------------------
```

**Comment by leoloso** [comment]
Run it again, but ignoring all packages starting with `migrate-`. The numbers will look much better.

There's a lot of old stuff there,  dating back to the pre-Composer architecture, so it's not PSR-4, not SOLID, and even contains some `vendor` folder. I'm migrating this code to proper, modern code, but it takes time.

Btw, most of this code has already been migrated for the plugin. The great bulk is in package [`migrate-everythingelse`](https://github.com/leoloso/PoP/blob/master/layers/Schema/packages/migrate-everythingelse/) which will be needed for the [Wassup layer](https://github.com/leoloso/PoP/tree/master/layers/Wassup/packages), which I'm not working on for the time being (I'm currently focused on the GraphQL API plugin)

So then, to be more precise, run your analysis again, ignoring `migrate-*`, and only containing [layers](https://github.com/leoloso/PoP/tree/master/layers) `Engine`, `API`, `Schema`, `GraphQLByPoP` and `GraphQLAPIForWP` (the ones used by the GraphQL API plugin). Numbers should look good.

> 300k JSON

I don't know where that comes from. The only `.json` files in the repo are all the `composer.json`. Since there are over 210 packages, then it might come from there. If that's the case, I see no problem.

Then, for JS, I'm allowing certain files compiled for production, to avoid the need to install all the `node_modules` folders.

For instance, that's the case for all the Gutenberg blocks [here](https://github.com/leoloso/PoP/tree/master/layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/blocks). There are 16 blocks in total. I can't expect anyone to have to install 16 `node_modules` folders just to run the webserver for development. So the compiled blocks can be committed to the repo (for instance, [this one](https://github.com/leoloso/PoP/blob/master/layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/blocks/access-control-disable-access/build/index.js))

And then, there's the [Service Workers compiled file for the Voyager client](https://github.com/leoloso/PoP/blob/master/layers/GraphQLByPoP/packages/graphql-clients-for-wp/clients/voyager/assets/vendors/voyager.worker.js), to show the Interactive Schema in the plugin. It's 1.89 MB of generated stuff, it doesn't look nice but there's no way around it.

**Comment by szepeviktor** [comment]
Okay - Okay. I do not play with the lion! 🦁
