### ISSUE TITLE
Sharing variables and objects is a basic necessity

### ISSUE THREAD

**Issue by szepeviktor** [leoloso/PoP#599]
From https://github.com/leoloso/PoP/blob/f134be00ccf8e4b4ce788dbd4d801e5641834b3a/layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/phpstan.neon.dist#L13

## Detailed description

# 🦕

Global constants `return \GRAPHQL_API_DIR;`
and static properties, functions `protected static $instance;`

# 👴

[A DI container](https://github.com/szepeviktor/injector-php-7) and [an immutable container](https://github.com/szepeviktor/small-project/blob/346d4c3008a2fc67f47df19a5b54c9546a27f135/plugin-name.php#L75-L86) are the object oriented solutions. Available since early PHP versions.

I let you take the wheel!

**Comment by leoloso** [comment]
All the `protected static $instance;` are in all the `migrate-*` packages, which you can completely ignore. I'm still in the process of migrating them to proper PSR-4, fully container-based code, but it's taking time.

Thanks for sharing your DI proposals, but I'm actually already using [Symfony's DependencyInjection](https://symfony.com/doc/current/components/dependency_injection.html), and it works beautifully!

For instance, [these are some of the services defined by the plugin](https://github.com/leoloso/PoP/blob/8cbefe122cc0b3e62000aed63a19471631aad95e/layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/config/services.yaml).

Btw, I only recently finished migrating all code to use the service container, so only now I'm finally able to finish the [documentation on the site](https://graphql-api.com/guides), to explain how to extend the GraphQL API with custom logic (custom types, field resolvers, directives, etc).

As for `return \GRAPHQL_API_DIR;`, alright, doing `Config::init(...)` instead sounds like a good idea. Wanna take care of it?

About `message: '#^Parameter \#1 \$str of function trim expects string, null given\.$#'`, what's up with that? I added a comment there:

```
# This error seems to be some bug from PHPStan, since param #1 is a string when run in context of WP
```

I haven't checked if it still happens... Do you know? Once the problem is fixed, I'll remove that error exception.

**Comment by szepeviktor** [comment]
PHPStan does not intended to handle non-OOP code.

I think this helps.

```neon
parameters:
    dynamicConstantNames:
        - GRAPHQL_API_DIR
```

and of course defining it in a bootstrap file.

**Comment by szepeviktor** [comment]
It can be debugged this way: `\PHPStan\dumpType(\GRAPHQL_API_DIR);`

**Comment by leoloso** [comment]
Ok, I'll check it out

**Comment by szepeviktor** [comment]
GitHub search says `GRAPHQL_API_PLUGIN_NAME` is only defined, not used :(

**Comment by szepeviktor** [comment]
Happy WP plugins do not ever see global constants 🤖😃

**Comment by leoloso** [comment]
> GitHub search says `GRAPHQL_API_PLUGIN_NAME` is only defined, not used :(

Yep, I need to remove it
