### ISSUE TITLE
Please raise visibility of Contributing

### ISSUE THREAD

**Issue by szepeviktor** [leoloso/PoP#619]
In the README you don't really find the _Contributing_ section, and it is so short one may think _I should not really contribute here_.
Please consider this.

**Comment by leoloso** [comment]
Currently, the README indicates that there's a CONTRIBUTING file specially devoted to that, [this one](https://github.com/leoloso/PoP/blob/master/CONTRIBUTING.md).

Is this not good enough? What changes do you propose?

I'm OK adding changes, but I don't know myself what changes are needed.

Btw, this format of README + CONTRIBUTING, I took it from [thephpleague/skeleton](https://github.com/thephpleague/skeleton)

**Comment by szepeviktor** [comment]
This is what I'm talking about.

![kép](https://user-images.githubusercontent.com/952007/115115460-e02db480-9f94-11eb-9838-5ec9723fbc3b.png)

**Comment by szepeviktor** [comment]
Basically take these use cases.

1. A user of PoP reads the README -> What section are relevant to him?
2. A developer/contributor reads the README -> What section are relevant to him?

I'd move may of current section to another file.

**Comment by szepeviktor** [comment]
BTW What does _PoP_ mean?

**Comment by leoloso** [comment]
> BTW What does _PoP_ mean?

It means "Platform of Platforms".

The name comes from the idea that websites built using this framework can talk to each other. Like with the IndieWeb, but already native to the framework itself: the component model over which it's based is a specification, i.e. it's itself a language, so any website could consume the information from any other website.

**Comment by leoloso** [comment]
> Basically take these use cases.
> 
>     1. A user of PoP reads the README -> What section are relevant to him?
> 
>     2. A developer/contributor reads the README -> What section are relevant to him?
> 
> 
> I'd move many of current sections to another file. E.g. short README + documentation for users + 1 document for contributors.

Actually, the repo is targetting only developers.

To target users, there are the websites:

- https://getpop.org <= for the PoP framework <= It's a bit abandoned currently, I will invest energy in it again after the `SiteBuilder` layer is finished
- https://graphql-by-pop.com <= for GraphQL by PoP, the CMS-agnostic GraphQL server layer
- https://graphql-api.com <= for the GraphQL API for WordPress plugin

If you check the README, all information is useful to developers. In order:

- Projects hosted in the repo, and their dependency graph
- PHP features for development
- How to start the Lando webserver for development
- Composer scripts for development

There are no sections for users.

And also, notice that each layer has its own README. For instance, the [`Schema` layer's README](https://github.com/leoloso/PoP/tree/master/layers/Schema) explains a bit how to create resolvers. So the root repo's README is not even as long as it could be.

So, do you think that I should split the README into a proper documentation, and show a TOC only?

**Comment by szepeviktor** [comment]
> Actually, the repo is targetting only developers.

Of course both of them are developers :)

Developer type 1 uses your code. "User"
Developer type 2 contributes to your code. "Developer"

I leave it up to you.

**Comment by szepeviktor** [comment]
As I see currently no one contributes to PoP, so the README should talk to users (developers who build on top of PoP). The next part of README should walk through things contributors do in chronological order.
You could call me and we can become users and developers and simulate the reading of README.

**Comment by szepeviktor** [comment]
Contributors do things like

1. understand the big picture
2. prepare development environment
3. write code
4. send PR


...just a few from the top of my head.

**Comment by leoloso** [comment]
It's true that there are no contributors yet, but I'm doing my best to welcome them if/whenever they show up. I'm very bad at promoting my projects. So it's going to take time, and I'll have to work hard for it.

Part of the issue is (I believe) that the [guides to add extensions](https://graphql-api.com/guides/) are still all empty, so nobody has an idea how to extend the GraphQL API. If they can't even start playing with it, then of course nobody will show up to contribute.

I've only recently finished working on the service container, after which I could create extensions. I've also created 2 extensions (one with directives, one an integration with the Events Manager plugin). I plan to release all of this in the upcoming v0.8, hopefully next week. Only then, I'll be able to complete the guides.

Then, truth is that the competition from WPGraphQL is tough, they are the most visible option. So I'll also be [working soon on the "Private GraphQL API"](https://github.com/leoloso/PoP/issues/519), to enable plugin developers to bundle the GraphQL API on their own plugins, self-contained, fully scoped. Let's see. Maybe it becomes a popular way to add GraphQL to Gutenberg blocks, and then I start having contributors. I hope so. I cross my fingers.

Either case, I have no clear response. I'm still working my hardest to make it happen, and hopefully it will eventually happen.

**Comment by szepeviktor** [comment]
You see! They have these

![kép](https://user-images.githubusercontent.com/952007/115119060-dd3bbf80-9fa6-11eb-8777-77fb3d10eed4.png)

and one-line installation

![kép](https://user-images.githubusercontent.com/952007/115119087-f3498000-9fa6-11eb-9a8b-c78fd586942e.png)

their documentation takes you step-by-step in easy-to-advanced order.

**Comment by leoloso** [comment]
All of that has to be done. They have contributors, who have worked on that project for years.

I'm working alone on this project, and there are so many things to do, and so little time.

If it has to be done, I'll do it, but everything take time.

Btw, the setup for my project is much more difficult. It's a monorepo. And it's intimidating (not many people like monorepos, I found out).

**Comment by szepeviktor** [comment]
> I'm working alone on this project, and there are so many things to do, and so little time.

No-no-no!
This project also has a lengthy README. But order and content (UX) matters.

**Comment by szepeviktor** [comment]
> Btw, the setup for my project is much more difficult. It's a monorepo. And it's intimidating (not many people like monorepos, I found out).

Please provide something like `composer require getpop/pop` for all use cases.

**Comment by leoloso** [comment]
> Please provide something like `composer require getpop/pop` for all use cases: PHP lib, library for a WordPress plugin, WordPress plugin etc.

Cannot, you need a `composer.json` with plenty of components to have the server working, like [this one](https://github.com/leoloso/PoP/blob/master/webservers/graphql-by-pop/composer.json#L47-L85).

That's why I created the WordPress plugin, so people could just install it, they way they know how to.

But I haven't uploaded the plugin to the wp.org repo yet. I could do it, but I'd like the plugin to be a bit more complete by then, as to avoid breaking changes (for instance, completely migrating all the `migrate-*` packages)

**Comment by leoloso** [comment]
You need to add in `composer.json`:

```json
{
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by szepeviktor** [comment]
> Cannot, you need a `composer.json` with plenty of components to have the server working, like [this one](https://github.com/leoloso/PoP/blob/master/webservers/graphql-by-pop/composer.json#L47-L85).

Isn't is possible to create an empty packages that requires everything?

**Comment by leoloso** [comment]
Can, that's actually what the WordPress plugin does.

**Comment by szepeviktor** [comment]
If cortex if not yet released, fork it and give it a stable version!

**Comment by leoloso** [comment]
Thing is, the target should be for people to install the plugin, and not manually install packages via Composer.

**Comment by leoloso** [comment]
Actually, I could ask the owner to create a release. Cortex has not been developed in like 7 years, I believe. So it's not under development anymore

**Comment by szepeviktor** [comment]
So why have so many separate and public parts it the goal is to get WordPress plugin users??

**Comment by leoloso** [comment]
GraphQL by PoP is a CMS-agnostic PHP server, that's why so many parts, so any server for any framework (such as Laravel) could only use the packages it needs.

WordPress is exactly what you were requesting: a `composer.json` with all the required packages, for WordPress.

**Comment by leoloso** [comment]
And then, the plugin has extra logic, specific to WordPress. For instance, the Persisted Queries and Custom Endpoints features are based on CPTs.

**Comment by leoloso** [comment]
And they are fully-based on Gutenberg for editing them. So these things are WordPress-specific.

But otherwise, the same GraphQL server could be replicated for another framework.

**Comment by szepeviktor** [comment]
I think all use cases should always be able to be installed by `composer require vendor/package` - no extra nothing.
Extra things kill your projects!

**Comment by leoloso** [comment]
I can create that `composer.json`, that's no problem.

I must first ask the Cortex guy if he'd like to create a stable release.

**Comment by szepeviktor** [comment]
> I can create that `composer.json`

That won't work with `composer require`. Think with the head of the developer (DX) not yours.

**Comment by szepeviktor** [comment]
You can build highly complex things in the background but developers must not see any of them! They must experience one very simple package.

**Comment by leoloso** [comment]
Why will it not work?

I can create a `composer.json` that requires all the needed packages, and then I publish it on Packagist, then you `require` that one and it'll bring everything.

**Comment by leoloso** [comment]
Yeah, it will be one package. Called `graphql-by-pop/server` or something like that

**Comment by szepeviktor** [comment]
> I can create a `composer.json` that requires all the needed packages, and then I publish it on Packagist

Oh! :) Then it isn't a `composer.json` but a "package".

**Comment by leoloso** [comment]
It will be exactly the same as this one:

https://github.com/leoloso/PoP/blob/master/webservers/graphql-by-pop/composer.json#L47-L85

But without `"minimum-stability": "dev"`, and then published to Packagist.

**Comment by szepeviktor** [comment]
All right!
Please move development packages to `"require-dev"`

**Comment by leoloso** [comment]
Already have. All of those are needed for PROD

**Comment by szepeviktor** [comment]
Are you sure `leoloso/examples-for-pop` and the tracer tool is for PROD?

**Comment by leoloso** [comment]
`leoloso/examples-for-pop` would not be included, since it provides examples added to [newapi.getpop.org/graphiql](https://newapi.getpop.org/graphiql), not needed for everyone. And the tracer tool, yes, it can make it to PROD, since the GraphQL API in PROD could perfectly be analyzed, to check how effective queries are. (And then, it's enabled/disabled via an environment variable)

However, today I woke up thinking, what do you want this package for?

If it is for PROD, you already have the WordPress plugin. You can install it as usual, or via Composer like explained in [the plugin's README](https://github.com/leoloso/PoP/tree/master/layers/GraphQLAPIForWP/plugins/graphql-api-for-wp#composer).

If if is for development, to contribute to the project, then I'm already offering a simple way to set-up the environment, explained in the README here: https://github.com/leoloso/PoP#lando-server-for-the-graphql-api-for-wordpress

This needs [Lando](https://docs.lando.dev/), though. But it's needed because of the monorepo, as to be able to edit the source code from any of the packages. If you do `composer require graphql-by-pop/server` and this package uses `pop-schema/posts` and you need to modify the field resolver for posts, you couldn't do it directly. But with the Lando set-up you can, because the local dependencies are not downloaded from Packagist, but symlinked to their source in the monorepo.

I'm actively maintaining the Lando set-up, it's the one I use myself for development. You can check out all the overrides here: https://github.com/leoloso/PoP/blob/master/webservers/graphql-api-for-wp/.lando.yml#L16. And it also install an initial set of sample data (with persisted queries, custom endpoints, and access control lists), so it's practical.

Also, I was thinking that creating the new package would not be so simple: just doing `composer require graphql-by-pop/server` alone will not work. That's because the server also need some stuff in the `.htaccess`, as done here: https://github.com/leoloso/PoP/blob/master/webservers/graphql-by-pop/assets/.htaccess. So when installing the WordPress plugin, it already handles all this extra work. But installing from Composer, you'd have to do it yourself, making it difficult.

In this sense, the new issue I created, #620, I now think it's not such a good idea. If you can, please use the Lando set-up.

**Comment by szepeviktor** [comment]
@leoloso Now we really need easy-to-understand docs :) https://www.smashingmagazine.com/2021/04/making-graphql-work-in-wordpress/
